'anonymous user':
    - 'access content'
    - 'search content'
    - 'use text format comment'
'authenticated user':
    - 'access content'
    - 'use text format comment'
    - 'add media from remote sources'
    - 'import media'
admin:
    - 'access all views'
    - 'access content'
    - 'access content overview'
    - 'access overlay'
    - 'access statistics'
    - 'access the dashboard page'
    - 'access user profiles'
    - 'administer blocks'
    - 'administer menu'
    - 'administer nodes'
    - 'administer site configuration'
    - 'administer taxonomy'
    - 'administer permissions'
    - 'administer users'
    - 'bypass node access'
    - 'configure ombu site'
    - 'create page content'
    - 'create url aliases'
    - 'delete any page content'
    - 'delete own page content'
    - 'delete revisions'
    - 'edit any page content'
    - 'edit own page content'
    - 'edit supplementary content'
    - 'redirect from admin to dashboard'
    - 'revert revisions'
    - 'show dashboard toolbar'
    - 'use text format comment'
    - 'use text format default'
    - 'use tinymce html button'
    - 'view own unpublished content'
    - 'view post access counter'
    - 'view revisions'
    - 'view the administration theme'
editor:
    - 'access content overview'
    - 'access contextual links'
    - 'access overlay'
    - 'access the dashboard page'
    - 'administer menu'
    - 'administer nodes'
    - 'administer taxonomy'
    - 'create page content'
    - 'create url aliases'
    - 'delete any page content'
    - 'delete own page content'
    - 'delete revisions'
    - 'edit any page content'
    - 'edit own page content'
    - 'edit supplementary content'
    - 'redirect from admin to dashboard'
    - 'revert revisions'
    - 'show dashboard toolbar'
    - 'use text format comment'
    - 'use text format default'
    - 'view revisions'
    - 'view the administration theme'
