comment:
    format: comment
    editor: ''
    settings: false
    rdf_mapping: {  }
default:
    format: default
    editor: ckeditor
    settings:
        default: 1
        user_choose: 0
        show_toggle: 1
        theme: advanced
        language: en
        buttons:
            default:
                Bold: 1
                Italic: 1
                Underline: 1
                BulletedList: 1
                NumberedList: 1
                Link: 1
                Unlink: 1
                Format: 1
                Styles: 1
            drupal:
                media: 1
        toolbar_loc: top
        toolbar_align: left
        path_loc: bottom
        resizing: 1
        verify_html: 1
        preformatted: 0
        convert_fonts_to_spans: 1
        remove_linebreaks: 1
        apply_source_formatting: 0
        paste_auto_cleanup_on_paste: 0
        block_formats: 'p,address,pre,h2,h3,h4,h5,h6,div'
        css_setting: theme
        css_path: ''
        css_classes: "Arrows=li.arrows\r\nExternal=li.external\r\nDocument=li.document\r\nForm=li.form\r\nQuestion=li.question\r\nButton=a.btn\r\nInline List=ul.inline"
    rdf_mapping: {  }
php_code:
    format: php_code
    editor: ''
    settings: false
    rdf_mapping: {  }
plain_text:
    format: plain_text
    editor: ''
    settings: false
    rdf_mapping: {  }
