comment:
    format: comment
    editor: tinymce
    settings:
        default: 1
        user_choose: 0
        show_toggle: 0
        theme: advanced
        language: en
        buttons:
            default:
                bold: 1
                italic: 1
                link: 1
                unlink: 1
                removeformat: 1
            inlinepopups:
                inlinepopups: 1
            autoresize:
                autoresize: 1
            paste:
                paste: 1
        toolbar_loc: top
        toolbar_align: left
        path_loc: bottom
        resizing: 1
        verify_html: 1
        preformatted: 0
        convert_fonts_to_spans: 1
        remove_linebreaks: 0
        apply_source_formatting: 0
        paste_auto_cleanup_on_paste: 1
        block_formats: p
        css_setting: self
        css_path: ''
        css_classes: ''
    rdf_mapping: {  }
default:
    format: default
    editor: tinymce
    settings:
        default: 1
        user_choose: 0
        show_toggle: 0
        theme: advanced
        language: en
        buttons:
            default:
                bold: 1
                italic: 1
                bullist: 1
                numlist: 1
                link: 1
                unlink: 1
                removeformat: 1
            font:
                formatselect: 1
                styleselect: 1
            inlinepopups:
                inlinepopups: 1
            autoresize:
                autoresize: 1
            drupal:
                media: 1
        toolbar_loc: top
        toolbar_align: left
        path_loc: bottom
        resizing: 1
        verify_html: 1
        preformatted: 0
        convert_fonts_to_spans: 1
        remove_linebreaks: 0
        apply_source_formatting: 0
        paste_auto_cleanup_on_paste: 1
        block_formats: 'p,h2,h3,h4'
        css_setting: self
        css_path: ''
        css_classes: ''
    rdf_mapping: {  }
